// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// findWeiszfeldMedian
Rcpp::List findWeiszfeldMedian(Rcpp::List subsetAtomsList, double sigma, unsigned int maxit, double tol);
RcppExport SEXP Mposterior_findWeiszfeldMedian(SEXP subsetAtomsListSEXP, SEXP sigmaSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::List >::type subsetAtomsList(subsetAtomsListSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< unsigned int >::type maxit(maxitSEXP );
        Rcpp::traits::input_parameter< double >::type tol(tolSEXP );
        Rcpp::List __result = findWeiszfeldMedian(subsetAtomsList, sigma, maxit, tol);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
